#!/bin/sh
dir=_MTN/mtn2git
git="git -C $dir"
if [ ! -d _MTN ]; then
    echo "Usage: $0 [remote]"
    echo "You need to execute this from the repository root."
    exit 1
fi
if [ ! -d "$dir" ]; then
  if [ $# -lt 1 ]; then
    echo "Usage: $0 [remote]"
    echo "You need to specify a remote on first usage."
    echo "You can add more remotes using: $git remote add <name> <address>"
    exit 1
  fi
  mkdir -p $dir
  $git init --bare --initial-branch=trunk
  $git remote add origin "$1"
fi
mtn sy
touch $dir/marks1.txt $dir/marks2.txt
[ -f $dir/authors.txt ] || echo 'lapo@lapo.it = Lapo Luchini <lapo@lapo.it>' > $dir/authors.txt
mtn ls branches --ignore-suspend-certs | sort -V | awk '
  NR == 1 { base = $0; len = length(base) }
  { d = length($0) - len; print $0 " = " (d > 0 ? substr($0, len+2) : "trunk") }
' > $dir/branches.txt
mtn --quiet --authors=$dir/authors.txt --branches-file=$dir/branches.txt --import-marks=$dir/marks1.txt --export-marks=$dir/marks1.txt git_export | \
    $git fast-import --import-marks=marks2.txt --export-marks=marks2.txt
for r in $($git remote); do
  echo "Mirroring to: $r"
  $git push --mirror $r
done
